### ISSUE TITLE
How to generate ToJson for fields from superclass

### ISSUE THREAD

**Issue by JanuszHain** [google/json_serializable.dart#701] opened 2020-09-03 18:28 UTC
I have checked a lot of issues and I don't quite get how generator for toJson works.

My class: 

```dart
part 'box_attention_data.g.dart';

@JsonSerializable()
class BoxAttentionData extends WidgetItemNestedData {
  final String text;

  BoxAttentionData({@required this.text}) : super(WidgetItemType.box_attention);

  @override
  List<Object> get props => [text];

  factory BoxAttentionData.fromJson(Map<String, dynamic> json) =>
      _$BoxAttentionDataFromJson(json);

  Map<String, dynamic> toJson() => _$BoxAttentionDataToJson(this);
}
```

My abstract class:

```dart
abstract class WidgetItemNestedData extends Equatable {
  final WidgetItemType type;

  WidgetItemNestedData(this.type);

  Map<String, dynamic> toJson();
}

enum WidgetItemType {
  card_contact_info,
  card_action,
  box_attention,
  list_info,
  expandable_list,
  checklist,
  empty_space,
  card_photo,
  simple_photo,
  static_simple_card,
  unknown,
}
```

The generated file:

```dart
part of 'box_attention_data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BoxAttentionData _$BoxAttentionDataFromJson(Map<String, dynamic> json) {
  return BoxAttentionData(
    text: json['text'] as String,
  );
}

Map<String, dynamic> _$BoxAttentionDataToJson(BoxAttentionData instance) =>
    <String, dynamic>{
      'text': instance.text,
    };

```

What I want in generated file is to have field `type` from superclass.

I have tried overriding getter and annotating it:

```dart
  @override
  @JsonKey(name: 'type')
  WidgetItemType get type => super.type;
```

The only thing that worked was setting it in constructor:

`BoxAttentionData({@required this.text, WidgetItemType type = WidgetItemType.box_attention}) : super(type);`

The problem is I don't think it is good idea to pass that in constructor (I prefer to do that in super, so nobody can setup different type than intended). Is there any other way to make it working?

**Comment by kevmoo** [comment] 2020-09-07 23:19
Duplicate of https://github.com/google/json_serializable.dart/issues/496 – more or less

**Closed by kevmoo** 2020-09-07 23:19 UTC
