### ISSUE TITLE
How to exclude field from toJson serialization?

### ISSUE THREAD

**Issue by AlexanderShniperson** [google/json_serializable.dart#1100] opened 2022-02-17 14:22 UTC
Hi

Currently `JsonKey` annotation have `ignore` parameter, but it's generalized for both `fromJson` and `toJson`.
The idea is to have a control over which fields can be serialized via `toJson` method and then sent over internet.

Could there be implemented additional parameter `bool? excludeToJson` ?

**Comment by JulianSwales** [comment] 2022-03-16 14:27
I'd actually like the above and one step further.. I have a backend SQL database that on Inserts has some Not Null with default database fields. So whilst I'm using this solution, toJson converts to a null value as it should when it's a nullable field, but if it's null on the data side I'd like to exclude the field in the toJson.. 
So I need the option above for things like the id field that's automatically generated on insert, but also an option to dynamically exclude fields based on their value.

**Comment by kevmoo** [comment] 2022-11-17 23:21
Duplicate of #569 

Trying to align all of these requests into one place!

**Closed by kevmoo** 2022-11-17 23:21 UTC

**Comment by kevmoo** [comment] 2022-11-22 01:43
I have a (draft) PR out on this. I'd LOVE (early) feedback about if this works for what folks need here: https://github.com/google/json_serializable.dart/pull/1256

I still need to do some documentation and testing...

**Comment by kevmoo** [comment] 2022-11-22 01:46
@JulianSwales – please open a separate issue for your request!
