### ISSUE TITLE
Because json_annotation >=4.1.0 depends on meta ^1.4.0 and every version of flutter from sdk depends on meta 1.3.0, json_annotation >=4.1.0 is incompatible with flutter from sdk.

### ISSUE THREAD

**Issue by daviinjuguna** [google/json_serializable.dart#962] opened 2021-08-09 17:58 UTC
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this, please include the entire output
of either `dart --version` or `flutter --version`, depending on what
you're using.

Is it really an issue? For general questions consider starting with Stack
Overflow:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/build

**Comment by kevmoo** [comment] 2021-08-10 01:23
Duplicate of https://github.com/google/json_serializable.dart/issues/944

**Closed by kevmoo** 2021-08-10 01:23 UTC

**Comment by agustdaegu** [comment] 2021-08-12 22:35
I had the same problem error. to fix it I've just used an older version.

```
json_annotation: ^4.0.1

dev_depencies:
...
json_serializable: ^4.1.4

```

**Comment by kevmoo** [comment] 2021-09-08 17:07
Flutter 2.5 stable is out!
