### ISSUE TITLE
[Feature Request] Allow specifying json path expression instead of just key name

### ISSUE THREAD

**Issue by soumyamahunt** [google/json_serializable.dart#1075] opened 2021-12-28 06:32 UTC
There are many scenarios where the json map is nested with multiple level of hierarchy, and creating a model only to retrieve one such map is not a good experience. Allowing to specify [JsonPath](https://goessner.net/articles/JsonPath/index.html#e2) expression in such scenario will be a really welcome change.

For example in the following json:
```json
{
    "coord": {
        "lon": -0.13,
        "lat": 51.51
    },
    "weather": [
        {
            "id": 300,
            "main": "Drizzle",
            "description": "light intensity drizzle",
            "icon": "09d"
        }
    ],
    "base": "stations",
    "main": {
        "temp": 280.32,
        "pressure": 1012,
        "humidity": 81,
        "temp_min": 279.15,
        "temp_max": 281.15
    },
    "visibility": 10000,
    "wind": {
        "speed": 4.1,
        "deg": 80
    },
    "clouds": {
        "all": 90
    },
    "dt": 1485789600,
    "sys": {
        "type": 1,
        "id": 5091,
        "message": 0.0103,
        "country": "GB",
        "sunrise": 1485762037,
        "sunset": 1485794875
    },
    "id": 2643743,
    "name": "London",
    "cod": 200
}
```
if I want weather id, name and temperature my model will look like this:
```dart
@JsonSerializable()
class WeatherData {

  String name;

  @JsonKey(path: '$.main.temp')
  double temp;

  @JsonKey(path: '$.weather[0].id')
  int weatherId;

  factory WeatherData.fromJson(Map<String, dynamic> json) =>
      _$WeatherDataFromJson(json);
  Map<String, dynamic> toJson() => _$WeatherDataToJson(this);
}
```

**Comment by kevmoo** [comment] 2021-12-28 23:40
Duplicate of https://github.com/google/json_serializable.dart/issues/490

**Closed by kevmoo** 2021-12-28 23:40 UTC
