### ISSUE TITLE
Generated .g.dart file incorrectly using const value from class

### ISSUE THREAD

**Issue by chirag729** [google/json_serializable.dart#975] opened 2021-09-08 18:24 UTC
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "linux_x64"

I have a serializable class which declares several static const values. One of them:

``` 
  static const int stateCreated = 0;
```
is somehow incorrectly being included in the generated .g.dart file:

```
      flags: json['f'] as int? ?? 0,
      state: json['s'] as int? ?? stateCreated,
```

instead of 

```
      flags: json['f'] as int? ?? 0,
      state: json['s'] as int? ?? 0,
```

This causes a compiler error and I have to manually change the value to '0' every time I re-generate with build runner

**Comment by kevmoo** [comment] 2021-09-08 18:26
I believe this is a duplicate of https://github.com/google/json_serializable.dart/issues/946

**Closed by kevmoo** 2021-09-08 18:26 UTC
