### ISSUE TITLE
Serialize multiple JSON key in a single variable

### ISSUE THREAD

**Issue by Softkeydel** [google/json_serializable.dart#888] opened 2021-05-11 18:00 UTC
With GSON we can do
@SerializedName(value="data", alternate={"variations", "products"})
@Expose
 private Data data;

How to implement the same with
@JsonKey(name: "location")

**Comment by kenan0620** [comment] 2021-05-12 06:31
> 使用GSON，我们可以执行
> @SerializedName（value =“ data”，Alternative = {“ variations”，“ products”}）
> @expose
> 私有数据数据；
> 
> 如何使用
> @jsonkey（名称：“位置”）实现相同功能

me too.
i want more to one field mapping. 

but eg is can't

@JsonKey(name: 'entity')
@JsonKey(name: 'items')

  List<String> list;

**Comment by k-paxian** [comment] 2021-05-12 14:56
something like [that](https://github.com/k-paxian/dart-json-mapper#name-aliases-configuration)?

**Comment by kenan0620** [comment] 2021-05-13 06:57
> something like [that](https://github.com/k-paxian/dart-json-mapper#name-aliases-configuration)?

tks,you are right, but u dart_json_mapper lib is old,
reason:Because no versions of json_serializable match >3.5.1 <4.0.0 and json_serializable 3.5.1 depends on build >=0.12.6 <2.0.0, json_serializable ^3.5.1 requires build >=0.12.6 <2.0.0.
u can update lib at someday? tks

**Comment by k-paxian** [comment] 2021-05-13 09:04
> > something like [that](https://github.com/k-paxian/dart-json-mapper#name-aliases-configuration)?
> 
> tks,you are right, but u dart_json_mapper lib is old,
> reason:Because no versions of json_serializable match >3.5.1 <4.0.0 and json_serializable 3.5.1 depends on build >=0.12.6 <2.0.0, json_serializable ^3.5.1 requires build >=0.12.6 <2.0.0.
> u can update lib at someday? tks

actually it's opposite, `json_serializable 3.5.1 depends on build >=0.12.6 <2.0.0`  and dart_json_mapper depends on `build ^2.0.1`
so you can use [previous version](https://pub.dev/packages/dart_json_mapper/versions/2.0.9) to be compatible alongside latest `json_serializable`

**Comment by kenan0620** [comment] 2021-05-14 06:02
> > > something like [that](https://github.com/k-paxian/dart-json-mapper#name-aliases-configuration)?
> > 
> > 
> > tks,you are right, but u dart_json_mapper lib is old,
> > reason:Because no versions of json_serializable match >3.5.1 <4.0.0 and json_serializable 3.5.1 depends on build >=0.12.6 <2.0.0, json_serializable ^3.5.1 requires build >=0.12.6 <2.0.0.
> > u can update lib at someday? tks
> 
> actually it's opposite, `json_serializable 3.5.1 depends on build >=0.12.6 <2.0.0` and dart_json_mapper depends on `build ^2.0.1` so you can use [previous version](https://pub.dev/packages/dart_json_mapper/versions/2.0.9) to be compatible alongside latest `json_serializable`

tks,tks for u help, it's very good. i like it

**Comment by kenan0620** [comment] 2021-05-14 06:24
> > > something like [that](https://github.com/k-paxian/dart-json-mapper#name-aliases-configuration)?
> > 
> > 
> > tks,you are right, but u dart_json_mapper lib is old,
> > reason:Because no versions of json_serializable match >3.5.1 <4.0.0 and json_serializable 3.5.1 depends on build >=0.12.6 <2.0.0, json_serializable ^3.5.1 requires build >=0.12.6 <2.0.0.
> > u can update lib at someday? tks
> 
> actually it's opposite, `json_serializable 3.5.1 depends on build >=0.12.6 <2.0.0` and dart_json_mapper depends on `build ^2.0.1` so you can use [previous version](https://pub.dev/packages/dart_json_mapper/versions/2.0.9) to be compatible alongside latest `json_serializable`

i was try it, but it's not my want.

**Comment by kenan0620** [comment] 2021-05-14 06:28
> > > something like [that](https://github.com/k-paxian/dart-json-mapper#name-aliases-configuration)?
> > 
> > 
> > tks,you are right, but u dart_json_mapper lib is old,
> > reason:Because no versions of json_serializable match >3.5.1 <4.0.0 and json_serializable 3.5.1 depends on build >=0.12.6 <2.0.0, json_serializable ^3.5.1 requires build >=0.12.6 <2.0.0.
> > u can update lib at someday? tks
> 
> actually it's opposite, `json_serializable 3.5.1 depends on build >=0.12.6 <2.0.0` and dart_json_mapper depends on `build ^2.0.1` so you can use [previous version](https://pub.dev/packages/dart_json_mapper/versions/2.0.9) to be compatible alongside latest `json_serializable`

i was try it, but it's not my want.

like this.

{data:''}
{'entity':''}
{'item':''}

i want more map to one. eg: 
class Model{
string : servicedata;
}

result: data && item && entity  map to servicedata.

tks

**Comment by kevmoo** [comment] 2021-11-26 22:56
Duplicate of https://github.com/google/json_serializable.dart/issues/144 – which I'm looking at now!

**Closed by kevmoo** 2021-11-26 22:56 UTC
Labels: Type: enhancement
