### ISSUE TITLE
UnimplementedError: (TypeParameterTypeImpl) T

### ISSUE THREAD

**Issue by mohan-sai-manthri-sg** [google/json_serializable.dart#1065] opened 2021-12-13 04:21 UTC
#  json_serializable: ^6.1.1

### Metrics reponse

``` dart
import 'package:json_annotation/json_annotation.dart';

import 'metrics_series.dart';

part 'metrics_response.g.dart';

@JsonSerializable(genericArgumentFactories: true)
class MetricsResponse<T> {
  MetricsResponse({this.type, this.queryType, this.series});

  factory MetricsResponse.fromJson(
    Map<String, dynamic> json,
    T Function(dynamic json) fromJsonT,
  ) =>
      _$MetricsResponseFromJson(json, fromJsonT);

  String? queryType;
  MetricsSeries<T>? series;
  String? type;

  Map<String, dynamic> toJson(dynamic Function(T value) toJsonT) =>
      _$MetricsResponseToJson(this, toJsonT);
}
```

### Metrics Series

``` dart
import 'package:json_annotation/json_annotation.dart';

import 'metrics_values.dart';

part 'metrics_series.g.dart';

@JsonSerializable(genericArgumentFactories: true)
class MetricsSeries<T> {
  MetricsSeries({this.start, this.end, this.values});

  factory MetricsSeries.fromJson(
    Map<String, dynamic> json,
    T Function(dynamic json) fromJsonT,
  ) =>
      _$MetricsSeriesFromJson(json, fromJsonT);

  String? end;
  String? start;
  List<MetricsValues<T>>? values;

  Map<String, dynamic> toJson(dynamic Function(T value) toJsonT) =>
      _$MetricsSeriesToJson(this, toJsonT);
}

```
###  Verbose

> [SEVERE] json_serializable:json_serializable on lib/features/dashboard/data/models/metrics_response.dart:
> 
> UnimplementedError: (TypeParameterTypeImpl) T
> package:json_serializable/src/utils.dart 208:3                      typeToCode
> dart:_internal                                                      ListIterable.join
> package:json_serializable/src/utils.dart 204:48                     typeToCode
> package:json_serializable/src/type_helpers/json_helper.dart 133:17  JsonHelper.deserialize
> package:json_serializable/src/type_helper_ctx.dart 68:29            TypeHelperCtx.deserialize.<fn>
> dart:core                                                           Iterable.firstWhere
> package:json_serializable/src/type_helper_ctx.dart 88:46            TypeHelperCtx._run
> package:json_serializable/src/type_helper_ctx.dart 65:19            TypeHelperCtx.deserialize
> package:json_serializable/src/decode_helper.dart 208:10             DecodeHelper._deserializeForField.deserialize
> package:json_serializable/src/decode_helper.dart 230:17             DecodeHelper._deserializeForField
> package:json_serializable/src/decode_helper.dart 56:9               DecodeHelper.createFactory.deserializeFun
> package:json_serializable/src/decode_helper.dart 332:32             _writeConstructorInvocation.<fn>
> dart:core                                                           StringBuffer.writeAll
> package:json_serializable/src/decode_helper.dart 330:9              _writeConstructorInvocation
> package:json_serializable/src/decode_helper.dart 59:18              DecodeHelper.createFactory
> package:json_serializable/src/generator_helper.dart 85:28           GeneratorHelper.generate
> dart:_internal                                                      WhereIterator.moveNext
> package:json_serializable/src/json_part_builder.dart 64:27          _UnifiedGenerator.generate
> package:source_gen/src/builder.dart 341:23                          _generate
> 
> [SEVERE] json_serializable:json_serializable on lib/features/dashboard/data/models/metrics_series.dart:
> 
> UnimplementedError: (TypeParameterTypeImpl) T
> package:json_serializable/src/utils.dart 208:3                         typeToCode
> dart:_internal                                                         ListIterable.join
> package:json_serializable/src/utils.dart 204:48                        typeToCode
> package:json_serializable/src/type_helpers/json_helper.dart 133:17     JsonHelper.deserialize
> package:json_serializable/src/type_helper_ctx.dart 68:29               TypeHelperCtx.deserialize.<fn>
> dart:core                                                              Iterable.firstWhere
> package:json_serializable/src/type_helper_ctx.dart 88:46               TypeHelperCtx._run
> package:json_serializable/src/type_helper_ctx.dart 65:19               TypeHelperCtx.deserialize
> package:json_serializable/src/type_helpers/iterable_helper.dart 76:32  IterableHelper.deserialize
> package:json_serializable/src/type_helper_ctx.dart 68:29               TypeHelperCtx.deserialize.<fn>
> dart:core                                                              Iterable.firstWhere
> package:json_serializable/src/type_helper_ctx.dart 88:46               TypeHelperCtx._run
> package:json_serializable/src/type_helper_ctx.dart 65:19               TypeHelperCtx.deserialize
> package:json_serializable/src/decode_helper.dart 208:10                DecodeHelper._deserializeForField.deserialize
> package:json_serializable/src/decode_helper.dart 230:17                DecodeHelper._deserializeForField
> package:json_serializable/src/decode_helper.dart 56:9                  DecodeHelper.createFactory.deserializeFun
> package:json_serializable/src/decode_helper.dart 332:32                _writeConstructorInvocation.<fn>
> dart:core                                                              StringBuffer.writeAll
> package:json_serializable/src/decode_helper.dart 330:9                 _writeConstructorInvocation
> package:json_serializable/src/decode_helper.dart 59:18                 DecodeHelper.createFactory
> package:json_serializable/src/generator_helper.dart 85:28              GeneratorHelper.generate
> dart:_internal                                                         WhereIterator.moveNext
> package:json_serializable/src/json_part_builder.dart 64:27             _UnifiedGenerator.generate
> package:source_gen/src/builder.dart 341:23                             _generate
> 

### Flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.22000.348], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] IntelliJ IDEA Community Edition (version 2021.2)
[√] VS Code (version 1.63.0)
[√] Connected device (3 available)

• No issues found!
```

### Flutter Version

> Flutter 2.8.0 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision cf44000065 (3 days ago) • 2021-12-08 14:06:50 -0800
> Engine • revision 40a99c5951
> Tools • Dart 2.15.0
>

**Comment by YoussefRaafatNasry** [comment] 2021-12-13 07:50
Duplicate of #1047.

**Comment by mohan-sai-manthri-sg** [comment] 2021-12-13 07:57
@YoussefRaafatNasry I cannot downgrade version as there are other dependent packages.

**Comment by YoussefRaafatNasry** [comment] 2021-12-13 08:23
I am just mentioning that it's being tracked on #1047.
I want to use `v6.X.X` too, let's hope it gets fixed soon.

**Comment by kevmoo** [comment] 2021-12-16 18:10
Closing as duplicate of https://github.com/google/json_serializable.dart/issues/1047

**Closed by kevmoo** 2021-12-16 18:10 UTC

**Comment by kevmoo** [comment] 2021-12-16 19:42
Fix published - https://pub.dev/packages/json_serializable/changelog#612
