### ISSUE TITLE
Serialize private field

### ISSUE THREAD

**Issue by Nico04** [google/json_serializable.dart#537] opened 2019-09-10 17:14 UTC
I am very surprised I can't serialize a basic private field, I guess it is by design because as soon as I make it public, it works well.

I have a quite basic use case.
I have a private field storing a global id count, used to generate local id of child objects.
So other object should have access to nextCatId or nextDogId but not _nextId.
And _nextId must be saved and loaded locally in my document-based dababase.

```
int _nextId = 0;
String get nextCatId => "c${nextId++}";
String get nextDogId => "h${nextId++}";
```

Any thoughts ?

**Comment by bsutton** [comment] 2019-10-24 00:10
I also had this problem and took some time to work out what was going one.

If you have a setter and a getter the json will be generated.

The documentation should note the fact that private fields are not generated.

I would argue that private fields should be supported as I may need to deserialise json into a class but not want to expose some internal fields outside of the class.

**Comment by k-paxian** [comment] 2019-12-19 14:31
@bsutton Agree on your point regarding private fields, and with all that my library 
https://github.com/k-paxian/dart-json-mapper supports getters only serialization if you are looking for alternatives of course.

**Comment by bsutton** [comment] 2019-12-22 22:43
@k-paxian thanks for the link. I've passed it onto the team member looking after a json code bits.

**Comment by vargavince91** [comment] 2020-06-25 13:07
I would love to be able to serialize private fields.

My use-case: I would like to serialize and deserialize the state`*` of the application with [`hydrated_bloc`](https://pub.dev/packages/hydrated_bloc), but some of the values I'm serializing *can* be private to the state, so I'd like to keep them private.

The workaround I found is using the `@visibleForTesting` annotation to make sure that I don't use the field elsewhere in my codebase.

```dart
// The JsonSerializable and JsonKey are just examples, their args could be anything else
@JsonSerializable(
  fieldRename: FieldRename.snake,
  ignoreUnannotated: true,
  includeIfNull: false,
)
class TheState {
  @JsonKey()
  @visibleForTesting // <--- important part
  final DateTime theField;
}
```

The solution works, but it could cause some confusion. The annotation communicates that the field had to be made visible for testing, instead of communicating that the field was made public for serialization. Maybe you actually want to test through other methods or getters, in which case making the field visible via `@visibleForTesting` can cause issues once someone has to write new or update old tests.



The [`dart-json-mapper`](https://github.com/k-paxian/dart-json-mapper) library from k-paxian looks great, but to be honest, I don't feel like updating my whole codebase to use that library only for this feature.

`*` actually the bloc itself, but I'm just delegating the serialization to the state

**Comment by matthew-carroll** [comment] 2020-09-14 07:18
In addition to the general and reasonable utility of saving private fields, the situation that I'm currently running into is that I had to destructure `Alignment` and `Rect` because I couldn't figure out how to implement a `TypeHelper`. As a result, I have a bunch of private fields for things like `left`, `top`, `right`, `bottom`, `x`, `y`, and none of these should be public, but I need them in my serialized JSON.

**Comment by mateusfccp** [comment] 2021-09-16 13:59
I deprecated some fields in my model but as I couldn't make them private I have to use them internally, so I get warnings from the linter.

Having this would probably solve my problem.

**Comment by ncuillery** [comment] 2022-04-13 13:59
My code is full of @visibleForTesting workaround occurrences (mentioned above). This feature would be really useful 🙏

**Comment by ambstuc** [comment] 2022-07-23 16:50
For some reason, the @visibleForTesting did not work for me. I had a private field _uuid in my class, and noting the comment by @bsutton above, I added a getter (which I needed anyway) and an empty setter:
```
String _uuid = Uuid().toString();
String get uuid => _uuid;
// workaround for json_serializable
set uuid(_) {}
```

That worked for me.

**Comment by kevmoo** [comment] 2022-11-17 23:21
Duplicate of #569 

Trying to align all of these requests into one place!

**Closed by kevmoo** 2022-11-17 23:21 UTC
Labels: Type: enhancement, pkg:json_serializable

**Comment by kevmoo** [comment] 2022-11-22 01:42
I have a (draft) PR out on this. I'd LOVE (early) feedback about if this works for what folks need here: https://github.com/google/json_serializable.dart/pull/1256

I still need to do some documentation and testing...
