### ISSUE TITLE
Gracefully handle unsupported enum values

### ISSUE THREAD

**Issue by via-guy** [google/json_serializable.dart#838] opened 2021-03-18 13:55 UTC
Currently when an unsupported enum value is found the decoder throws an `ArgumentError`. This can completely break an app in production when an enum value is added to the server.

Currently the only option is to add an `xUnknown` value to each enum, which seems completely unnecessary for a nullable value.

It would be great to either add a new property to `JsonKey`, e.g. `allowUnsupportedEnumValue`, or handle the same logic if both `nullable == true` and `unknownEnumValue == null`.

```
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (8 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5
```

**Comment by jeiea** [comment] 2021-05-06 01:24
Is it a duplicate of #559?

**Comment by via-guy** [comment] 2021-05-06 07:36
@jeiea I guess it is.

**Comment by kevmoo** [comment] 2021-07-13 23:16
Duplicate of https://github.com/google/json_serializable.dart/issues/559

**Closed by kevmoo** 2021-07-13 23:16 UTC
Labels: Area: enums
