### ISSUE TITLE
Not possible to map to nested fields @JsonKey(name: "inner.name")

### ISSUE THREAD

**Issue by venil7** [google/json_serializable.dart#871] opened 2021-04-10 20:35 UTC
```
flutter --version                                                                                                              1 ↵
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (9 days ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2
```
Not possible to map to inner/nested maps or arrays
```
@JsonKey(name: "inner.name")
String name;
```

**Comment by kevmoo** [comment] 2021-04-10 23:50
Duplicate of https://github.com/google/json_serializable.dart/issues/490

**Comment by kevmoo** [comment] 2021-04-10 23:50
Duplicate of https://github.com/google/json_serializable.dart/issues/490

**Closed by kevmoo** 2021-04-10 23:50 UTC
