### ISSUE TITLE
No mapper is generated for stanadlone enum files that aren't part of any class

### ISSUE THREAD

**Issue by agilob** [google/json_serializable.dart#784] opened 2021-01-03 09:10 UTC
No mapper is generated for an enum when the enum isn't used in any class and has its own file, but has fields annotated with `@JsonValue`. Since `@JsonSerializable` is allowed only on classes, not enums, there's no way to deserialize such enums.

Enum also has `part x.g.dart`, but it's never generated.

**Comment by kevmoo** [comment] 2021-07-28 01:37
Duplicate of https://github.com/google/json_serializable.dart/issues/778

**Closed by kevmoo** 2021-07-28 01:37 UTC
Labels: Area: enums, Type: enhancement
