### ISSUE TITLE
How to let the  generated code  in another directory?

### ISSUE THREAD

**Issue by dinoandcat** [google/json_serializable.dart#886] opened 2021-05-08 10:49 UTC
When I have a lot of models , there will a lot of  generated code files  in the same directory. 
I want to move the generated code files to a directory like this:
```
├─model
│  │  note.dart
│  │  note_table.dart
│  │  todo.dart
│  │  todo_item.dart
│  │  user.dart
│  │
│  └─json
│          note.g.dart
│          todo.g.dart
│          todo_item.g.dart
│          user.g.dart

```

**Comment by kevmoo** [comment] 2021-05-24 20:21
Duplicate of https://github.com/google/json_serializable.dart/issues/347

**Closed by kevmoo** 2021-05-24 20:21 UTC
