### ISSUE TITLE
Allow specifying the output folder

### ISSUE THREAD

**Issue by devteam-tchs** [google/json_serializable.dart#720] opened 2020-09-19 14:07 UTC
Versions:

```
Flutter 1.20.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 216dee60c0 (3 weeks ago) • 2020-09-01 12:24:47 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```

Reasoning:

I feel that the generated files creates a mess, especially if you have a lot of classes like I do. I would like to move all the generated stuff to its own folder like `__generated__` for example so that I don't have to look at them while I'm actively developing. This could be added as an option in the `build.yaml` for example and allow you to use an absolute route to a folder or have it be relative to where the class is located.

**Comment by kevmoo** [comment] 2020-09-19 15:12
Duplicate of # https://github.com/google/json_serializable.dart/issues/306

**Closed by kevmoo** 2020-09-19 15:12 UTC
