### ISSUE TITLE
nested attribute without JsonKey

### ISSUE THREAD

**Issue by Babwenbiber** [google/json_serializable.dart#913] opened 2021-06-10 05:53 UTC
I want to parse this json:
```
{
    "class_a_attr_1": 23,
    "class_b_attr_1": "foo",
    "class_b_attr_2": 5
}
```
Into this class

```
class classA {
  final int attr1;
  final classB;
}
```
When my class B has a fromJson already with assigning classAttr1 and classAttr2.
The current problem is, that the lib expects my json to have this form:
```
{
    "class_a_attr_1": 23,
    "class_b": 
     {
       "class_b_attr_1": "foo",
       "class_b_attr_2": 5
    }
}
```
How can I pass the json to classB without any key?

**Comment by k-paxian** [comment] 2021-06-16 16:50
it's already requested [here](https://github.com/google/json_serializable.dart/issues/853)

**Comment by kevmoo** [comment] 2021-07-13 20:58
Yup. Closing as duplicate of https://github.com/google/json_serializable.dart/issues/853

**Closed by kevmoo** 2021-07-13 20:58 UTC
